[project]
name = "achaekek"
version = "0.0.13"
description = "Python library for the Manifold markets API."
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "TetraspaceW", email = "holomanga@gmail.com" }]
dependencies = ["requests>=2.31.0"]

[dependency-groups]
dev = ["pytest>=8", "python-dotenv>=1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
